//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTRKApp.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PTRKBaseEntities1 : DbContext
    {
        public PTRKBaseEntities1()
            : base("name=PTRKBaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<group> group { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<Sbor> Sbor { get; set; }
        public virtual DbSet<uche_sbora> uche_sbora { get; set; }
    }
}
