//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTRKApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class uche_sbora
    {
        public int id_uchet { get; set; }
        public int id_product { get; set; }
        public int id_group { get; set; }
        public int Days_sbora { get; set; }
        public int kg_sbora { get; set; }
        public System.DateTime Date_sbora { get; set; }
    
        public virtual group group { get; set; }
        public virtual product product { get; set; }
    }
}
